name: Deploy Admin Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          REACT_APP_API_HOST: ${{ secrets.REACT_APP_API_HOST }}
          REACT_APP_AUTH0_DOMAIN: ${{ secrets.REACT_APP_AUTH0_DOMAIN }}
          REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.REACT_APP_AUTH0_CLIENT_ID }}
          REACT_APP_AUTH0_AUDIENCE: ${{ secrets.REACT_APP_AUTH0_AUDIENCE }}

      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          source: "build/*"
          target: "/var/www/hakka-admin"
          strip_components: 1

      - name: Setup permissions
        run: |
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > temp_ssh_key
          chmod 600 temp_ssh_key
          ssh -o StrictHostKeyChecking=no -i temp_ssh_key ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            chown -R www-data:www-data /var/www/hakka-admin
            chmod -R 755 /var/www/hakka-admin
          EOF
          rm -f temp_ssh_key